sonar.organization=devopsuc3m-gr84-a
sonar.projectKey=DevOpsUC3M-gr84-A_DevOps-gr84-A
sonar.projectName=NEWSRADAR
sonar.projectVersion=1.3

# --- AJUSTE DE RUTAS ---
# Le decimos que la raíz de búsqueda es el repositorio completo
sonar.sources=.
# Pero le obligamos a que solo analice el código real del backend
sonar.inclusions=newsradar_api/app/**

# Indicamos donde están los tests para que no los cuente como código a cubrir
sonar.tests=newsradar_api/tests
sonar.test.inclusions=newsradar_api/tests/**

# Exclusiones estándar
sonar.exclusions=**/__pycache__/**, **/*.pyc, venv/**, docs/**, newsradar_ui/**

# --- REPORTE DE COBERTURA ---
# Como ahora el XML se genera desde la raíz, esta ruta es la correcta
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8