# 1. Identificadores del proyecto en SonarCloud
sonar.organization=devopsuc3m-gr84-a
sonar.projectKey=DevOpsUC3M-gr84-A_DevOps-gr84-A

# 2. Metadatos
sonar.projectName=NEWSRADAR
sonar.projectVersion=1.1

# 3. Configuración de análisis (Solo analizamos el backend real)
sonar.sources=newsradar_api/app
sonar.language=py
sonar.python.version=3.11

# 4. Exclusiones (Ignoramos dependencias, tests y archivos autogenerados)
sonar.exclusions=**/__pycache__/**, **/*.pyc, venv/**, docs/**

# 5. Reporte de cobertura de código
sonar.python.coverage.reportPaths=coverage.xml