name: CI/CD Frontend - Validate and Deploy

on:
  push:
    branches:
      - main
    paths:
      - "newsradar_ui/**"
      - ".github/workflows/cd-frontend.yml"
  pull_request:
    branches:
      - main
    paths:
      - "newsradar_ui/**"
      - ".github/workflows/cd-frontend.yml"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build-and-test:
    name: Build and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "newsradar_ui/package-lock.json"

      - name: Install dependencies
        working-directory: newsradar_ui
        run: npm i

      - name: Build React app
        working-directory: newsradar_ui
        run: npm run build

      # 5. Deploy solo si estamos en main y no es un Pull Request
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./newsradar_ui/build
          cname: ""
          force_orphan: true
