name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-frontend:
    name: Run React Tests
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./newsradar_ui

    steps:
      # Descargar el código del repositorio en la máquina virtual
      - name: Checkout del código
        uses: actions/checkout@v4

      # Preparar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./newsradar_ui/package-lock.json

      # Instalar las dependencias
      - name: Instalar dependencias
        run: npm ci

      # Ejecutar tests
      - name: Ejecutar Tests de Jest
        run: npm test
        env:
          CI: true